export enum constants {
    GET_SLOTS_REQUEST = "GET_SLOTS_REQUEST",
    GET_SLOTS_SUCCESS = "GET_SLOTS_SUCCESS",
    GET_SLOTS_FAILURE = "GET_SLOTS_FAILURE",
    SCHEDULE_SLOT_REQUEST = "SCHEDULE_SLOT_REQUEST",
    SCHEDULE_SLOT_SUCCESS = "SCHEDULE_SLOT_SUCCESS",
    SCHEDULE_SLOT_FAILURE = "SCHEDULE_SLOT_FAILURE"
  }
  
export enum status{
  BOOKED='Booked',
  AVAILABLE='Available',
  NOT_AVAILABLE='Not Available'
}